name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - name: Fix Jasmine permissions
        run: chmod +x ./node_modules/.bin/jasmine  

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t calculator:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag calculator:latest ${{ secrets.DOCKER_USERNAME }}/calculator:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/calculator:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Save the SSH private key to a file
          echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          # Use SSH to deploy the Docker image
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa $SSH_USER@$SERVER_IP << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/calculator:latest
            docker stop calculator || true
            docker rm calculator || true
            docker run -d -p 80:80 --name calculator ${{ secrets.DOCKER_USERNAME }}/calculator:latest
          EOF
